### ISSUE TITLE
Error during proof generation

### ISSUE THREAD

**Issue by lgiussan** [maxgillett/giza#10]
# Issue description

I am trying to generate a proof for the following simple program `program.cairo`:
```
func main():
    alloc_locals
    local n
    %{ ids.n = program_input['n'] %}
    empty_loop(n)
    ret
end

func empty_loop(n):
    if n == 0:
        ret
    end
    empty_loop(n-1)
    ret
end
```
Proof generation is successful if `n <= 15`, but fails if `n > 15` with the following error:
```
thread 'main' panicked at 'index out of bounds: the len is 69 but the index is 69', runner/src/runner.rs:405:9
```

# How to reproduce

To reproduce, run:
```
cairo-compile program.cairo --output=program.json &&
cairo-run --layout=all --program=program.json --program_input=input.json --trace_file=trace.bin --memory_file=memory.bin &&
giza prove --program=program.json --trace=trace.bin --memory=memory.bin --output=output.bin
```
where the content of `input.json` is either
```
{ "n": 15 }
```
for successful proof generation, or
```
{ "n": 16 }
```
for triggering the error.

# Suggested fix

It should be possible to fix the issue by changing line `runner/src/trace.rs:246` from
```
let mut state = State::new(mem.size() as usize);
```
to
```
let mut state = State::new(registers.len());
```

**Comment by maxgillett** [comment]
Thanks! I just fixed this in the latest commit on master.
