### ISSUE TITLE
Is this prover compatible with the Starkware onchain smart-contract ?

### ISSUE THREAD

**Issue by tdelabro** [maxgillett/giza#16]
Can I feed the trace and proof generated by Giza into the "official" starknet verifier ?

**Comment by xhliu** [comment]
Same question. https://github.com/starkware-libs/starkex-contracts/tree/master/evm-verifier

**Comment by tdelabro** [comment]
@maxgillett Do you know ?

**Comment by maxgillett** [comment]
It is not. One of the major differences is in the layout, with more columns present in the Giza execution trace than what is prepared by SHARP, (as Starkware is optimizing for verification time/cost over proving time). It would be interesting to list out all the changes that need to be made to make it compatible.

**Comment by xhliu** [comment]
giza would be much more useful if it is with official Starkware verifier. Look forward to the changes to make this happen.

**Comment by maxgillett** [comment]
@xhliu, you may want to check out https://github.com/andrewmilson/sandstorm, which is focused on SHARP compatibility. Closing this issue for now.
