### ISSUE TITLE
giza-examples panicked

### ISSUE THREAD

**Issue by xhliu** [maxgillett/giza#17]
```
cargo run --release --bin giza-examples
     Running `target/release/giza-examples`
thread 'main' panicked at 'index out of bounds: the len is 24 but the index is 24', runner/src/memory.rs:99:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Same error as in #10.

**Comment by maxgillett** [comment]
I believe issue https://github.com/maxgillett/giza/issues/18 is the culprit here. Can you try generating a proof using an external Cairo runner?

**Comment by xhliu** [comment]
You mean generating using StarkNet's SHARP?

**Comment by maxgillett** [comment]
@xhliu, I mean generating using the Starkware Python runner (or the LambdaClass Rust runner). Closing this issue for now.
